spring:
  application:
    name: thecart-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///Users/aseshres/project/git-config-local-repo
          search-paths:
            - 'catalog*'
server:
  port: 8888

